services:
  - type: web
    name: erp-backend
    env: node
    plan: free
    rootDir: backend
    buildCommand: npm install && npm run build
    startCommand: npm run start
    envVars:
      - key: SUPABASE_URL
        fromSecret: supabase-url
      - key: SUPABASE_ANON_KEY
        fromSecret: supabase-anon-key
      - key: JWT_SECRET
        fromSecret: jwt-secret
      - key: JWT_EXPIRES_IN
        value: "7d"
  - type: static_site
    name: erp-frontend
    plan: free
    rootDir: frontend
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    routes:
      - type: proxy
        source: /api/*
        destination: https://super-sun-app.onrender.com/api/:splat
    envVars:
      - key: VITE_API_URL
        value: /api/v1
